version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    assignees:
      - mcgroarty
    groups:
      astro:
        patterns:
          - "astro"
          - "@astrojs/*"
      dev-dependencies:
        dependency-type: development

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    assignees:
      - mcgroarty
